### ISSUE TITLE
DroidFix.install(this); 有疑问。

### ISSUE THREAD

**Issue by wogenhaosini** [bunnyblue/DroidFix#12]
里面的源码
`public static void install(Context context) {
        Log.i(TAG, "install");

        File dexDir = new File(context.getFilesDir(), DROID_CODE_CACHE);
        try {
            File shell = ZipUtil.copyAsset(context, "shell.apk", dexDir);
            ArrayList<File> files = new ArrayList<File>();
            files.add(shell);
            Log.i("quanbin", files.size()+"");
            installDex(context.getClassLoader(), dexDir, files, false);
        } catch (IOException e) {
            e.printStackTrace();
        } catch (InvocationTargetException e) {
            e.printStackTrace();
        } catch (NoSuchMethodException e) {
            e.printStackTrace();
        } catch (NoSuchFieldException e) {
            e.printStackTrace();
        } catch (InstantiationException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        }
    }`

demo中并没有`assets`  也并没有`shell.apk`  我把 `DroidFix.install(this);` 同时也是正常运行，是否是多余代码？

**Comment by bunnyblue** [comment]
这个是https://github.com/bunnyblue/DroidFix/tree/master/AntilazyLoad，自己产生个apk就行了，如果你你不放的话页没事，就是满屏的warning
