### ISSUE TITLE
关于AntilazyLoad  类的插入

### ISSUE THREAD

**Issue by hnlbxb2004** [bunnyblue/DroidFix#13]
我看到，在使用这个热补丁的时候，需要给每个类都插入  AntilazyLoad  这个类，但是我没有看到怎么插入的这个类，或者说什么时候插入的？（本人菜鸟，麻烦赐教）

**Comment by bunnyblue** [comment]
Application attach的时候插入。需要打补丁的类都要插入，具体原因看readme

**Comment by hnlbxb2004** [comment]
不是这个问题，我是说需要给每个类插入这个AntilazyLoad 这个类，不是问AntilazyLoad 在 Application attach的时候插入。
 
我忽然找到了，是在gradle 里面配置的执行的，

  task.doLast {
            javaexec {
                classpath "$rootDir/ClassComputer.jar"
                main = 'io.github.bunnyblue.droidfix.classcomputer.ClassComputer'
                args "injectCode", projectDir.getAbsolutePath(), "releaseDroidFix"
            }
            javaexec {
                classpath "$rootDir/ClassComputer.jar"
                main = 'io.github.bunnyblue.droidfix.classcomputer.ClassComputer'
                args "diffPatch", projectDir.getAbsolutePath(), "releaseDroidFix"
            }
            javaexec {
                classpath "$rootDir/ClassComputer.jar"
                main = 'io.github.bunnyblue.droidfix.classcomputer.ClassComputer'
                args "buildPkg", projectDir.getAbsolutePath(),"patch"
            }

        }

应该是这个。

**Comment by bunnyblue** [comment]
在执行dex之前，dex之前计算class的md5 计算完成插入，然后在编译成dex

**Comment by hnlbxb2004** [comment]
恩，找到代码位置了。
