### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by zmc0218** [bunnyblue/DroidFix#15]
build.gradle里面的  “transformClassesAndResourcesWithProguardForRelease”   “transformClassesAndResourcesWithProguardForReleaseDroidFix”  这些字符串是怎么来的啊 在哪里查阅的。  还有   javaexec {
                classpath "$rootDir/ClassComputer.jar"
                main = 'io.github.bunnyblue.droidfix.classcomputer.ClassComputer'
                args "injectCode", projectDir.getAbsolutePath(), "releaseDroidFix"
            }

"releaseDroidFix" 字符串是根据什么定义的呢？  刚开始学这个，谢谢！

**Comment by bunnyblue** [comment]
ClassComputer中定义的参数

**Comment by zmc0218** [comment]
@bunnyblue  我想把这个集成到我的项目中，ClassComputer文件中需要怎么改啊 我一直编译不过。请加我qq吧，

**Comment by bunnyblue** [comment]
android gradle buildtool每次升级里面的可能会变，导致脚本不可用

**Comment by zmc0218** [comment]
@bunnyblue  哦  谢谢，我去研究gradle语法看看
