### ISSUE TITLE
支持的Android版本？

### ISSUE THREAD

**Issue by THEONE10211024** [bunnyblue/DroidFix#3]
请问有测试过Android的版本兼容没有？尤其是5.0以后的系统

**Comment by bunnyblue** [comment]
都支持

**Comment by bunnyblue** [comment]
6.0 上面直接加载apk会出现错误，不知道啥情况，先把dex压缩才行

**Comment by THEONE10211024** [comment]
不知道您有没有看过阿里推出的dexposed框架（https://github.com/alibaba/dexposed）这两者在原理上有何不同？因为阿里的这套框架对Art的虚拟机支持的不够好。想知道你在这方面怎么处理的～

**Comment by bunnyblue** [comment]
看过，阿里的那个hook了虚拟机，即时生效，这个参照的QQ方案，你可以看readme。里面有链接，Android 6.0测试了没问题，不过这个打补丁需要重启app

**Comment by THEONE10211024** [comment]
非常感谢您的分享，我还有一个担心是这个框架有经过非常详尽的测试没有？在所有机型和所有版本上是否都能良好运做～😄

**Comment by bunnyblue** [comment]
理论上是这样子，还没，最近忙，机器最高版本5.0.1  高版本用的模拟器

**Comment by THEONE10211024** [comment]
多谢！
